package kz.ask.shared.error;

public enum ErrorCode {

    USER_NOT_FOUND("Пользователь не найден"),
    CHALLENGE_NOT_FOUND("Код подтверждения не найден"),
    EMAIL_ALREADY_REGISTERED("Email уже зарегистрирован"),
    PHONE_ALREADY_REGISTERED("Телефон уже зарегистрирован"),
    EMAIL_ALREADY_EXISTS("Пользователь с таким email уже существует"),
    INVALID_CREDENTIALS("Неверный email или пароль"),
    ACCOUNT_NOT_ACTIVE("Аккаунт не активен"),
    ROLE_MISMATCH("Неверная роль аккаунта"),
    SESSION_INVALID("Сессия недействительна"),
    PASSWORD_CHANGE_NOT_REQUIRED("Смена пароля не требуется"),
    PASSWORDS_DO_NOT_MATCH("Пароли не совпадают"),
    TWO_FACTOR_STATE_CHANGED("Настройка двухфакторной защиты уже изменилась"),
    CHALLENGE_EXPIRED("Код подтверждения истек: %s"),
    CHALLENGE_MAX_ATTEMPTS("Превышено количество попыток: %s"),
    CHALLENGE_INVALID_CODE("Неверный код подтверждения: %s"),
    REGISTRATION_PAYLOAD_ERROR("Ошибка данных регистрации"),
    CITY_NOT_FOUND("Город не найден"),
    BUSINESS_NOT_FOUND("Бизнес не найден"),
    BRANCH_NOT_FOUND("Филиал не найден"),
    STAFF_NOT_FOUND("Сотрудник не найден"),
    STAFF_ALREADY_ACTIVATED("Сотрудник уже активировал аккаунт"),
    ACCESS_DENIED("Доступ запрещен"),
    DELIVERY_FAILED("Ошибка отправки кода подтверждения"),
    INTERNAL_ERROR("Внутренняя ошибка сервера"),
    IMPORT_NOT_FOUND("Импорт не найден"),
    IMPORT_NOT_XLSX("Файл должен быть в формате .xlsx"),
    IMPORT_EMPTY_FILE("Файл пуст"),
    IMPORT_INVALID_STATUS("Недопустимый статус импорта для этой операции"),
    IMPORT_NAME_REQUIRED("Название товара обязательно"),
    IMPORT_COLUMN_NOT_FOUND("Колонка не найдена: %s"),
    FILE_NOT_XLSX("Поддерживаются только файлы .xlsx"),
    REQUEST_NOT_FOUND("Запрос не найден"),
    CATEGORY_NOT_FOUND("Категория не найдена"),
    BUSINESS_SCOPE_REQUIRED("Укажите направление бизнеса"),
    PRODUCT_NOT_FOUND("Товар не найден для этого филиала"),
    SKU_ALREADY_EXISTS("SKU уже используется другим товаром в этом бизнесе"),
    PRODUCT_NAME_BLANK("Название товара не может быть пустым"),
    OPERATOR_FORBIDDEN_ACTION("Оператору не разрешено выполнять действие: %s"),
    DROP_NOT_FOUND("Дроп не найден"),
    DROP_DATA_INVALID("Unique Offer data is invalid"),
    DROP_RELATION_INVALID("Unique Offer contains an Item, Service, or Branch from another Business"),
    STOREFRONT_NOT_FOUND("Витрина не опубликована"),
    STOREFRONT_BLOCK_INVALID("Блок витрины некорректен"),
    CONTACT_NOT_FOUND("Контакт не найден"),
    CONTACT_ACTION_INVALID("Контактное действие недействительно"),
    CONTACT_ACTION_EXPIRED("Контактное действие истекло"),
    MEILISEARCH_INDEX_FAILED("Meilisearch index operation failed"),
    MEILISEARCH_DELETE_FAILED("Meilisearch delete operation failed"),
    MEILISEARCH_SEARCH_FAILED("Meilisearch search operation failed"),
    SEARCH_PROJECTION_VERSION_INVARIANT("Search projection version invariant failed"),
    SEARCH_PROJECTION_INVALID("Search projection data is incomplete"),
    AI_SEARCH_API_KEY_MISSING("DEEPSEEK_API_KEY is required for AI structured search"),
    AI_INTENT_STRUCTURE_FAILED("AI intent structure request failed"),
    AUTODUMP_INPUT_READ_FAILED("Не удалось прочитать файл импорта"),
    AUTODUMP_SESSION_NOT_FOUND("AI Autodump сессия не найдена"),
    AUTODUMP_DRAFT_NOT_FOUND("AI Autodump черновик не найден"),
    AUTODUMP_AI_JOB_NOT_FOUND("AI Autodump задача не найдена"),
    CONVERSATION_NOT_FOUND("Чат не найден"),
    BRANCH_REQUIRED_FOR_WORKER("Для сотрудника необходимо указать филиал"),
    INVITATION_NOT_FOUND("Приглашение не найдено"),
    INVITATION_ALREADY_PENDING("Активное приглашение уже существует"),
    INVITATION_NOT_PENDING("Приглашение больше не активно"),
    INVITATION_EMAIL_MISMATCH("Приглашение предназначено другому пользователю"),
    INVITATION_MEMBER_EXISTS("Пользователь уже состоит в этом бизнесе"),
    INVITATION_ROLE_NOT_ALLOWED("Эту роль нельзя назначить через приглашение"),
    LEGAL_DOCUMENT_NOT_FOUND("Active legal document not found"),
    ACCOUNT_OWNER_TRANSFER_REQUIRED("Transfer ownership or delete the owned business before deleting the account"),
    BUSINESS_ONBOARDING_INVALID("Business onboarding data is invalid"),
    MANAGED_IMPORT_NOT_FOUND("Managed import request not found"),
    MANAGED_IMPORT_ACTIVE_EXISTS("An active managed import already exists for this business"),
    MANAGED_IMPORT_FORBIDDEN("Managed import access is not allowed"),
    FILE_INVALID("Uploaded file is not allowed"),
    BUSINESS_MEDIA_NOT_FOUND("Business media file not found"),
    ATTACHMENT_NOT_FOUND("Attachment not found"),
    CONVERSATION_CLOSED("Чат закрыт"),
    PLATFORM_MEMBERSHIP_NOT_FOUND("Platform membership not found"),
    PLATFORM_MEMBERSHIP_EXISTS("Platform membership already exists"),
    BUSINESS_MEMBER_NOT_FOUND("Участник бизнеса не найден"),
    BUSINESS_MEMBER_ROLE_NOT_ALLOWED("Эту роль нельзя назначить участнику"),
    CONTENT_REPORT_NOT_FOUND("Content report not found"),
    CONTENT_REPORT_INVALID_STATUS("Content report can only be resolved or rejected"),
    CONTENT_REPORT_ALREADY_RESOLVED("Content report is already closed"),
    MODERATION_REJECT_REASON_REQUIRED("Причина отклонения обязательна"),
    CANNOT_DELETE_SELF("Невозможно удалить собственный аккаунт администратора"),
    CANNOT_DELETE_LAST_SUPER_ADMIN("Невозможно удалить последнего активного суперадминистратора"),
    BUSINESS_VERIFICATION_NOT_FOUND("Верификация бизнеса не найдена"),
    BRANCH_NOT_ALLOWED_ONLINE_ONLY("Нельзя создать филиал для онлайн-бизнеса");

    private final String template;

    ErrorCode(String template) {
        this.template = template;
    }

    public String format(Object... args) {
        if (args == null || args.length == 0) {
            return template;
        }
        return String.format(template, args);
    }
}
