package kz.ask.audit.domain.enums;

public enum SignificantEventType {
    BUSINESS_CREATED,
    BUSINESS_INVITATION_SENT,
    BUSINESS_INVITATION_ACCEPTED,
    BUSINESS_INVITATION_DECLINED,
    MANAGED_IMPORT_REQUESTED,
    MANAGED_IMPORT_STARTED,
    MANAGED_IMPORT_GRANT_CREATED,
    CATALOG_PUBLISHED,
    MANAGED_IMPORT_COMPLETED,
    MANAGED_IMPORT_GRANT_REVOKED,
    PRODUCT_HIDDEN_BY_MODERATOR,
    BUSINESS_SUSPENDED,
    BUSINESS_BANNED,
    EMAIL_CHANGED,
    ACCOUNT_DELETION_REQUESTED,
    ACCOUNT_DELETED
}
