spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ask
    username: ask_app
    password: 59wUTwwqJnYkWdGLo2zvpTJP8If75vb8
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jpa:
    show-sql: true
  mail:
    username: local-test@example.com
    password: local-test-password

server:
  port: 9090

auth:
  jwt:
    secret: local-development-secret-key-at-least-256-bits-long
  verification:
    email:
      enabled: false
    sms:
      enabled: false

springdoc:
  swagger-ui:
    enabled: true
