package kz.ask.identity.authorization.domain.enums;

public enum Permission {
    MANAGE_PLATFORM_USERS,
    MANAGE_MANAGED_IMPORTS,
    EDIT_ITEMS_SERVICES_DURING_IMPORT,
    USE_AI_ITEMS_SERVICES_TOOLS,
    PUBLISH_ITEMS_SERVICES_DURING_IMPORT,
    MANAGE_SUPPORT_CHATS,
    MODERATE_ITEMS,
    MODERATE_SERVICES,
    MODERATE_UNIQUE_OFFERS,
    MODERATE_BUSINESSES,
    MODERATE_BRANCHES,
    MODERATE_BUSINESS_MEMBERS,
    MODERATE_APP_USERS,
    MODERATE_CHATS,
    VIEW_MODERATION_QUEUE
}
